pads:
  - code: 36
    command: "OpenFolderCommand"
    folder_path: "C:/Users/Gjergji/Desktop"

  - code: 37
    command: "OpenFolderCommand"
    folder_path: "C:/Users/Gjergji/Repos"

#  - code: 38
#    command: "SwitchBackGroundCommand"
#    formal_background_path: "C:/Users/Gjergji/Pictures/Wallpapers/Hintergrund_Teams.png"
#    casual_background_path: "C:/Users/Gjergji/Pictures/Wallpapers/cyberpunk-2077-video-game-cyborg-girl-with-katana-wallpaper-3440x1440_15.jpg"

potentiometers:
  - code: 21
    command: "SetVolumeCommand"

  - code: 22
    command: "SetVolumeCommand"

  - code: 23
    command: "SetVolumeCommand"

  - code: 24
    command: "SetVolumeCommand"

  - code: 25
    command: "SetVolumeCommand"

  - code: 26
    command: "SetVolumeCommand"

  - code: 27
    command: "SetVolumeCommand"

  - code: 28
    command: "SetVolumeCommand"

play_rec:
  - code: 115
    command: "SwitchDeviceCommand"
    dll_path: "C:/Users/Gjergji/Repos/midi-controller/device-switcher/build/Release/OutputDeviceSwitcher.dll"

  - code: 117
    command: "KillProcessCommand"
    process_name: "pythonw.exe"

keys:
  - code: 48
    command: "TestCommand"
    message: "Test Command message"
    output: "Hello World"
